termId: 1 # enumerate {1: autumn, 2: winter, 3: spring, 5: summer}

username: 19123456 # your username

password: Abcde12345 # your password

courses:
  - courseId: 0830001 #(required) the course id you want to select
    teacherNo: 1001 #(required) the teacher_no you want to select
    courseName: 摸鱼学导论 #(optional) the course name
    teacherName: 张三 #(optional) the teacher name

  - courseId: 08300002
    teacherNo: 1002

  - courseId: 08300003
    teacherNo: 1003

  # you can add as many courses as you like below...